pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                git url: 'https://github.com/AndriiZil/jenkins-nodejs-test.git', branch: "master"
                echo "Code cloned successfully"
            }
        }
        stage('Test') {
            steps {
                sh 'ls'
            }
        }
    }
}
