pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                git url: 'https://github.com/AndriiZil/jenkins-nodejs-test.git', branch: "master"
                echo "Code cloned successfully"
            }
        }
        stage('Create Docker Image') {
            steps {
                sh 'docker build -t andriizilnyk/jenkins-nodejs-test:latest .'
            }
        }
        stage('Test Docker Image') {
            steps {
                sh 'docker inspect andriizilnyk/jenkins-nodejs-test:latest'
            }
        }
        stage('Publish Docker Image') {
            steps {
                sh "docker login -u andriizilnyk -p wp1jqQtCNpaf0e7fPIYg"
                sh 'docker push andriizilnyk/jenkins-nodejs-test:latest'
            }
        }
    }
}
